function dxd = dxdFunc(t)
%DXDFUNC
%    DXD = DXDFUNC(T)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    12-Dec-2019 00:51:03

t2 = t.*pi;
t3 = sin(t2);
t4 = t3.*pi.*(3.0./4.0);
dxd = [t4;t4];
