function xd = xdFunc(t)
%XDFUNC
%    XD = XDFUNC(T)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    12-Dec-2019 00:51:03

t2 = t.*pi;
t3 = cos(t2);
xd = [t3.*(-3.0./4.0)-3.0./4.0;t3.*(-3.0./4.0)+1.5e1./4.0];
